import type { Dial, L, Lang, Level } from '../engine/types';
import type { Phase } from '../state/console';

export const t = (l: L, lang: Lang) => l[lang];

/** 판매처·배송·주문 화면 문구 */
export const SV = {
  sellers: { ko: '판매처', en: 'Sellers' },
  nCompare: { ko: (n: number) => `${n}곳 가격 비교`, en: (n: number) => `Compare ${n}` },
  addFrom: { ko: (s: string, p: string) => `${s}에서 담기, ${p}`, en: (s: string, p: string) => `Add from ${s}, ${p}` },
  compareSellers: { ko: (n: number) => `판매처 ${n}곳 비교`, en: (n: number) => `Compare ${n} sellers` },
  freeShip: { ko: '무료배송', en: 'Free shipping' },
  shipFee: { ko: (s: string) => `배송비 ${s}`, en: (s: string) => `${s} shipping` },
  kind: {
    official: { ko: '브랜드 공식몰', en: 'Brand store' },
    select: { ko: '셀렉트숍', en: 'Select shop' },
    mall: { ko: '종합몰', en: 'Marketplace' },
    overseas: { ko: '해외직구', en: 'Overseas' },
  },
  price: { ko: '판매가', en: 'Price' },
  shipping: { ko: '배송비', en: 'Shipping' },
  landed: { ko: '배송비 포함', en: 'With shipping' },
  arrive: { ko: '도착', en: 'Arrival' },
  returns: { ko: '반품', en: 'Returns' },
  best: { ko: '총액 최저', en: 'Lowest total' },
  lowestTag: { ko: '표시가 최저', en: 'Lowest price' },
  noStock: { ko: '이 사이즈 없음', en: 'Not in this size' },
  addHere: { ko: '여기서 담기', en: 'Add from here' },
  pickSizeFirst: { ko: '사이즈를 먼저 고르세요', en: 'Pick a size first' },
  sheetNote: {
    ko: 'Nod는 판매자가 아니에요. 주문·배송·반품은 각 판매처가 처리해요.',
    en: 'Nod is not the seller. Each seller handles its own orders, shipping and returns.',
  },
  inCartAt: { ko: (s: string) => `${s}에 담김`, en: (s: string) => `In cart from ${s}` },
  // 장바구니·주문
  cartTab: { ko: '장바구니', en: 'Cart' },
  ordersTab: { ko: '주문 내역', en: 'Orders' },
  subtotal: { ko: '상품', en: 'Items' },
  shipTotal: { ko: '배송비', en: 'Shipping' },
  freeLeft: { ko: (s: string) => `${s} 더 담으면 이 판매처 무료배송`, en: (s: string) => `${s} more for free shipping here` },
  splitNote: { ko: (n: number) => `판매처 ${n}곳이라 주문도 ${n}건으로 나뉘어요.`, en: (n: number) => `${n} sellers, so this becomes ${n} orders.` },
  address: { ko: '배송지', en: 'Ship to' },
  addressV: { ko: '집 · 서울 성동구 연무장길 12, 302호', en: 'Home, 12 Yeonmujang-gil 302, Seongdong-gu, Seoul' },
  noOrders: { ko: '아직 주문이 없어요. 결제를 승인하면 판매처별 주문이 여기에 생겨요.', en: 'No orders yet. Approved payments show up here, one order per seller.' },
  orderNo: { ko: '주문번호', en: 'Order' },
  placedBy: { ko: { agent: '에이전트가 담고 내가 결제', user: '직접 결제' }, en: { agent: 'Added by the agent, paid by you', user: 'Paid by you' } },
  st: {
    paid: { ko: '결제 완료', en: 'Paid' },
    ready: { ko: '상품 준비 중', en: 'Preparing' },
    shipped: { ko: '출고', en: 'Shipped' },
    transit: { ko: '배송 중', en: 'In transit' },
    arrived: { ko: '도착', en: 'Delivered' },
  },
  expected: { ko: '예정', en: 'expected' },
  contact: { ko: (s: string) => `배송·반품 문의는 ${s}에 해요.`, en: (s: string) => `Ask ${s} about delivery and returns.` },
  orderCount: { ko: (n: number) => `주문 ${n}건`, en: (n: number) => `${n} order${n > 1 ? 's' : ''}` },
  payBreak: { ko: '판매처별 주문', en: 'Orders by seller' },
  duty: { ko: '관부가세가 따로 붙을 수 있어요', en: 'Import duties may apply' },
  // 알림
  added: { ko: '장바구니에 담았어요', en: 'Added to cart' },
  looking: { ko: '보는 중', en: 'Looking' },
  agentAdded: { ko: '에이전트가 장바구니에 담았어요', en: 'The agent added this to your cart' },
  removed: { ko: '장바구니에서 뺐어요', en: 'Removed from cart' },
  viewCart: { ko: '장바구니 보기', en: 'View cart' },
  addFail: {
    'sold-out': { ko: '방금 품절돼 담지 못했어요', en: 'Just sold out, not added' },
    size: { ko: '사이즈를 먼저 골라주세요', en: 'Pick a size first' },
    'other-size': { ko: '다른 사이즈로 이미 담겨 있어요. 장바구니에서 빼고 다시 담아주세요', en: 'Already in your cart in another size. Remove it first' },
    'other-seller': { ko: '다른 판매처에서 이미 담겨 있어요. 장바구니에서 빼고 다시 담아주세요', en: 'Already in your cart from another seller. Remove it first' },
    unknown: { ko: '담지 못했어요', en: 'Could not add' },
  },
  qtyMax: { ko: '이 판매처에 남은 재고가 더 없어요', en: 'No more stock at this seller' },
  priceMoved: { ko: '장바구니 상품 가격이 바뀌었어요', en: 'A price in your cart changed' },
  inCart: { ko: '담김', en: 'In cart' },
  less: { ko: '하나 빼기', en: 'One less' },
  plus: { ko: '하나 더', en: 'One more' },
  // 장바구니 변경·결제 확인
  changedTitle: { ko: '담은 뒤 바뀐 게 있어요', en: 'Some things changed since you added them' },
  changedFix: { ko: '지금 조건으로 고치기', en: 'Update to current terms' },
  changedPrice: { ko: (n: string, a: string, b: string) => `${n}: ${a}에서 ${b}로`, en: (n: string, a: string, b: string) => `${n}: ${a} to ${b}` },
  changedStock: { ko: (n: string, k: number) => (k === 0 ? `${n}: 품절` : `${n}: ${k}개만 남음`), en: (n: string, k: number) => (k === 0 ? `${n}: sold out` : `${n}: only ${k} left`) },
  toReview: { ko: '주문 확인으로', en: 'Review order' },
  reviewTitle: { ko: '결제 전 확인', en: 'Review before paying' },
  back: { ko: '장바구니로', en: 'Back to cart' },
  payMethod: { ko: '결제 수단', en: 'Payment' },
  payMethodV: { ko: '등록된 카드 •••• 4821', en: 'Saved card •••• 4821' },
  itemsTotal: { ko: '상품 금액', en: 'Items' },
  shipTotalL: { ko: '배송비', en: 'Shipping' },
  grand: { ko: '총 결제 금액', en: 'Total' },
  payN: { ko: (s: string) => `${s} 결제하기`, en: (s: string) => `Pay ${s}` },
  payBlocked: { ko: '바뀐 내용을 먼저 반영해주세요', en: 'Apply the changes first' },
  doneTitle: { ko: '주문을 완료했어요', en: 'Order placed' },
  doneSub: { ko: (n: number) => `판매처 ${n}곳에 주문이 접수됐어요. 배송과 반품은 각 판매처가 처리해요.`, en: (n: number) => `${n} seller${n > 1 ? 's' : ''} received your order. Each handles its own delivery and returns.` },
  willPlace: { ko: (n: number) => `결제하면 판매처 ${n}곳에 주문이 하나씩 접수돼요. 배송과 반품은 각 판매처가 처리해요.`, en: (n: number) => `Paying places one order with each of ${n} seller${n > 1 ? 's' : ''}. Each handles its own delivery and returns.` },
  keepShopping: { ko: '쇼핑 계속하기', en: 'Keep shopping' },
  overBy: { ko: (s: string) => `한도보다 ${s} 많아요`, en: (s: string) => `${s} over your limit` },
  underBy: { ko: (s: string) => `한도까지 ${s} 남아요`, en: (s: string) => `${s} left before your limit` },
  approvePayN: { ko: (s: string) => `${s} 결제`, en: (s: string) => `Pay ${s}` },
  approveOver: { ko: (s: string) => `한도를 넘지만 ${s} 결제`, en: (s: string) => `Pay ${s} over limit` },
  // 카드 정보
  reviewsN: { ko: (n: number) => `리뷰 ${n.toLocaleString('ko-KR')}`, en: (n: number) => `${n.toLocaleString('en-US')} reviews` },
  ratingL: { ko: (r: number) => `별점 ${r.toFixed(1)}`, en: (r: number) => `Rated ${r.toFixed(1)}` },
  likesL: { ko: (n: number) => `좋아요 ${n.toLocaleString('ko-KR')}`, en: (n: number) => `${n.toLocaleString('en-US')} likes` },
  // 처리 중
  holding: { ko: (s: string) => `${s} 재고 확인 중`, en: (s: string) => `Checking stock at ${s}` },
  checking: { ko: '재고와 가격을 확인하는 중', en: 'Checking stock and prices' },
  payingTitle: { ko: '결제를 진행하고 있어요', en: 'Processing your payment' },
  payingNote: { ko: '잠시만 기다려주세요. 판매처가 주문을 받으면 주문번호가 생겨요.', en: 'One moment. Each seller issues an order number when it accepts.' },
  payAuth: { ko: '결제 승인 요청', en: 'Requesting payment approval' },
  payAuthed: { ko: '결제 승인 완료', en: 'Payment approved' },
  sendTo: { ko: (s: string) => `${s}에 주문 전달`, en: (s: string) => `Sending order to ${s}` },
  acceptedBy: { ko: (s: string) => `${s} 주문 접수`, en: (s: string) => `${s} accepted` },
  confirming: { ko: '주문 확인 중', en: 'Confirming orders' },
  confirmed: { ko: '주문 확인 완료', en: 'Orders confirmed' },
  // 주문 상세·배송 조회
  orderDetail: { ko: '주문 상세', en: 'Order details' },
  viewDetail: { ko: '주문 상세 보기', en: 'View order details' },
  toOrders: { ko: '주문 내역으로', en: 'Back to orders' },
  moreItems: { ko: (n: number) => ` 외 ${n}건`, en: (n: number) => ` +${n} more` },
  tracking: { ko: '배송 조회', en: 'Tracking' },
  carrier: { ko: '배송사', en: 'Carrier' },
  invoice: { ko: '운송장 번호', en: 'Tracking no.' },
  noInvoice: { ko: '출고되면 운송장 번호가 생겨요', en: 'Issued when the order ships' },
  refresh: { ko: '새로고침', en: 'Refresh' },
  loadingTrack: { ko: '배송 정보를 불러오는 중', en: 'Loading tracking' },
  asOf: { ko: (s: string) => `${s} 기준`, en: (s: string) => `As of ${s}` },
  copy: { ko: '복사', en: 'Copy' },
  copied: { ko: '복사됨', en: 'Copied' },
  orderItems: { ko: '주문 상품', en: 'Items' },
  payInfo: { ko: '결제 정보', en: 'Payment' },
  paidAt: { ko: '결제 일시', en: 'Paid at' },
  shipInfo: { ko: '배송지 정보', en: 'Delivery' },
  shipReq: { ko: '요청사항', en: 'Note' },
  shipReqV: { ko: '문 앞에 놓아주세요', en: 'Leave at the door' },
  sellerInfo: { ko: '판매처', en: 'Seller' },
  orderedVia: { ko: '주문 방식', en: 'Placed' },
  expArrive: { ko: (s: string) => `${s} 예정`, en: (s: string) => `${s} (expected)` },
  liveChanged: { ko: '방금 판매처 조건이 바뀌었어요. 승인하면 결제하지 않고 바뀐 내용을 먼저 보여드려요.', en: 'Seller terms just changed. If you approve, you will see the changes before anything is paid.' },
} as const;

/** 에이전트 스레드 문구 */
export const TH = {
  byLlm: { ko: 'Claude가 해석', en: 'Read by Claude' },
  byRule: { ko: '규칙으로 해석', en: 'Read by rules' },
  byLlmNote: { ko: '요청을 Claude가 읽고, 쇼핑몰 조건으로 바꿨어요. 담기·결제 전에는 그대로 물어봐요.', en: 'Claude read the request and turned it into shop criteria. It still asks before adding and paying.' },
  byRuleNote: { ko: '정해 둔 규칙으로 요청을 읽었어요. 모르는 표현은 물어봐요.', en: 'The request was read with fixed rules. Unknown words are asked about.' },
  title: { ko: '에이전트', en: 'Agent' },
  skipped: { ko: '제외', en: 'Skipped' },
  settings: { ko: '맡기는 방식', en: 'How I work' },
  done: { ko: '접기', en: 'Done' },
  suggest: { ko: '이렇게 맡겨보세요', en: 'Try asking' },
  you: { ko: '나', en: 'You' },
  sellerWhy: { ko: '판매처를 고른 이유', en: 'Why this seller' },
  cartAsk: { ko: '이 상품을 담을까요?', en: 'Add this item?' },
  after: { ko: '담으면 합계', en: 'Cart after' },
  staleAdd: { ko: (a: string, b: string) => `방금 판매가가 ${a}에서 ${b}로 바뀌었어요. 승인해도 담지 않고 다시 물어볼게요.`, en: (a: string, b: string) => `The price just changed from ${a} to ${b}. If you approve, I will ask again before adding.` },
  limitOf: { ko: (s: string) => `한도 ${s}`, en: (s: string) => `Limit ${s}` },
  seeOrders: { ko: '주문 내역 보기', en: 'View orders' },
  log: { ko: '한 일', en: 'What I did' },
  sizeSum: { ko: '내 사이즈', en: 'My sizes' },
  payAsk: { ko: '결제를 승인할까요?', en: 'Approve payment?' },
  payNote: { ko: '승인하면 판매처마다 주문이 접수돼요. Nod는 판매자가 아니에요.', en: 'Approving places one order per seller. Nod is not the seller.' },
  more: { ko: '더 보기', en: 'More' },
  hello: { ko: '무엇을 찾아드릴까요? 담기 전과 결제 전에는 꼭 먼저 물어볼게요.', en: 'What should I find? I always ask before adding to cart and before paying.' },
  found: { ko: (n: number) => `후보 ${n}개를 골랐어요.`, en: (n: number) => `I shortlisted ${n}.` },
  added: { ko: '장바구니에 담았어요.', en: 'Added to your cart.' },
  askCartQ: { ko: (n: string) => `${n}, 담을까요?`, en: (n: string) => `Add ${n}?` },
  askPayQ: { ko: (a: string) => `${a} 결제할까요?`, en: (a: string) => `Pay ${a}?` },
  askPlanQ: { ko: '이 계획대로 시작할까요?', en: 'Start with this plan?' },
  doneTitle: { ko: '주문이 접수됐어요', en: 'Order placed' },
  stopTitle: { ko: '여기서 멈췄어요', en: 'Stopped here' },
  next: { ko: '이어서 맡겨보세요', en: 'Keep going' },
  arrive: { ko: '도착', en: 'Arrives' },
  paying: { ko: '결제를 진행하고 있어요', en: 'Processing your payment' },
  payingNote: { ko: '승인한 금액 그대로 결제해요. 판매처가 주문을 받으면 주문번호가 생겨요.', en: 'Charging exactly what you approved. Each seller issues an order number when it accepts.' },
  orderNo: { ko: '주문번호', en: 'Order no.' },
  paidWith: { ko: '결제 수단', en: 'Paid with' },
  tlPlaced: { ko: '주문 접수', en: 'Placed' },
  tlShip: { ko: '발송 예정', en: 'Ships' },
  tlArrive: { ko: '도착 예정', en: 'Arrives' },
  now: { ko: '지금', en: 'Now' },
  less: { ko: '접기', en: 'Less' },
  history: { ko: '기록', en: 'History' },
  whyHere: { ko: '왜 여기서?', en: 'Why here?' },
  step: { ko: (i: number, n: number) => `${i}/${n}단계`, en: (i: number, n: number) => `Step ${i}/${n}` },
  itemsN: { ko: (n: number) => `${n}개`, en: (n: number) => `${n} item${n > 1 ? 's' : ''}` },
  total: { ko: '결제 금액', en: 'Total' },
} as const;

export const SZ = {
  title: { ko: '내 사이즈', en: 'My sizes' },
  note: { ko: '에이전트가 담을 때 기본으로 씁니다. 미설정이면 담기 전에 물어봅니다.', en: 'Used by the agent when adding. If unset, it asks first.' },
  none: { ko: '미설정', en: 'Unset' },
  kind: { top: { ko: '상의·아우터', en: 'Tops' }, shoe: { ko: '신발', en: 'Shoes' }, bottom: { ko: '하의', en: 'Bottoms' } },
  pick: { ko: '사이즈', en: 'Size' },
  choose: { ko: '사이즈 선택', en: 'Select size' },
  other: { ko: '다른 사이즈', en: 'Other size' },
  saveNote: { ko: '이 기기에 저장해 두고 다음에도 씁니다.', en: 'Saved on this device for next time.' },
  change: { ko: '변경', en: 'Change' },
} as const;

export const C = {
  brand: { ko: 'Nod', en: 'Nod' },
  searchPh: { ko: '검색 (예: 검정 울 코트 20만원 이하)', en: 'Search (e.g. black wool coat under 200000)' },
  cart: { ko: '장바구니', en: 'Cart' },
  all: { ko: '전체', en: 'All' },
  scrubTitle: { ko: '행동 타임라인', en: 'Action timeline' },
  replay: { ko: '되감기 중', en: 'Replay' },
  live: { ko: '실시간', en: 'Live' },
  market: { ko: '지금 판매처에서', en: 'Live at sellers' },
  play: { ko: '처음부터 재생', en: 'Replay from start' },
  pause: { ko: '멈춤', en: 'Pause' },
  backToLive: { ko: '실시간으로', en: 'Back to live' },
  replayNote: { ko: '읽기 전용이에요. 지금 화면은 그 시점의 장바구니·재고·에이전트 상태예요.', en: 'Read-only. The screen shows cart, stock and agent state at that moment.' },
  themeToggle: { ko: '테마 전환', en: 'Toggle theme' },
  add: { ko: '담기', en: 'Add' },
  adding: { ko: '담는 중', en: 'Adding' },
  soldOut: { ko: '품절', en: 'Sold out' },
  left: { ko: '재고', en: 'Stock' },
  noResult: { ko: '조건에 맞는 상품이 없어요.', en: 'No products match.' },
  understoodAs: { ko: '이렇게 해석했어요', en: 'Interpreted as' },
  byAgent: { ko: '에이전트', en: 'Agent' },
  empty: { ko: '장바구니가 비었어요.', en: 'Your cart is empty.' },
  total: { ko: '합계', en: 'Total' },
  remove: { ko: '빼기', en: 'Remove' },
  checkout: { ko: '결제하기', en: 'Checkout' },
  orders: { ko: '주문 완료', en: 'Orders' },
  close: { ko: '닫기', en: 'Close' },

  agent: { ko: '쇼핑 에이전트', en: 'Shopping agent' },
  agentSub: { ko: '결제 직전까지 대신합니다', en: 'Everything up to checkout' },
  request: { ko: '요청', en: 'Request' },
  requestPh: { ko: '무엇을 찾아서 담아드릴까요?', en: 'What should I find and add?' },
  composerHint: { ko: '종류, 색, 예산, 사이즈, 언제까지 받을지 말해주세요', en: 'Say the item, color, budget, size, or when you need it' },
  send: { ko: '맡기기', en: 'Hand off' },
  busyHint: { ko: '찾는 중이에요. 결정이 필요하면 여기서 물어볼게요.', en: 'Working on it. I will ask here when I need you.' },
  open: { ko: '펼치기', en: 'Expand' },
  fold: { ko: '접기', en: 'Collapse' },
  presets: { ko: '자주 하는 요청', en: 'Popular requests' },
  dial: { ko: '자율도', en: 'Autonomy' },
  dialNote: { ko: '어떤 단계에서도 결제는 직접 승인해요.', en: 'You approve payment at every level.' },
  limit: { ko: '결제 한도', en: 'Payment limit' },
  run: { ko: '맡기기', en: 'Hand off' },
  rerun: { ko: '다시 맡기기', en: 'Run again' },
  reset: { ko: '초기화', en: 'Reset' },
  resetNote: { ko: '쇼핑몰(재고·장바구니)도 처음 상태로 돌아가요.', en: 'Also restores the shop (stock and cart).' },

  planTitle: { ko: '에이전트의 계획', en: "Agent's plan" },
  approveStart: { ko: '이대로 시작', en: 'Start' },
  cancel: { ko: '취소', en: 'Cancel' },
  approveCart: { ko: '담기', en: 'Add' },
  skipCart: { ko: '담지 않기', en: "Don't add" },
  compare: { ko: '나란히 비교', en: 'Compare' },
  candidates: { ko: '후보', en: 'Candidates' },
  askTitle: { ko: '에이전트가 묻고 있어요', en: 'The agent needs your input' },
  payTitle: { ko: '결제 직전 승인', en: 'Pre-payment approval' },
  limitShort: { ko: '한도', en: 'Limit' },
  exceeded: {
    ko: '한도를 넘었어요. 자율도와 관계없이 직접 확인이 필요해요.',
    en: 'Over your limit. Needs your review regardless of autonomy level.',
  },
  approvePay: { ko: '결제', en: 'Pay' },
  declinePay: { ko: '결제 안 함', en: "Don't pay" },
  audit: { ko: '행동 기록', en: 'Action audit' },
  auditEmpty: { ko: '아직 행동이 없어요.', en: 'No actions yet.' },
  undo: { ko: '되돌리기', en: 'Undo' },
  undone: { ko: '되돌림', en: 'Undone' },
  removedByYou: { ko: '장바구니에서 직접 뺌', en: 'Removed from cart by you' },
  ordered: { ko: '주문됨', en: 'Ordered' },
  idle: { ko: '요청을 입력하거나 자주 하는 요청을 골라 맡겨보세요.', en: 'Type a request or pick a popular one.' },
  statusRunning: { ko: '진행 중', en: 'In progress' },
  statusWaiting: { ko: '승인 대기', en: 'Awaiting approval' },
  statusDone: { ko: '완료', en: 'Done' },
  statusFailed: { ko: '실패', en: 'Failed' },
} satisfies Record<string, L>;

/** 맡길 수 있는 일의 예. 상황별로 묶어 보여준다. */
export const SUGGEST: { g: L; items: { text: L; label?: L }[] }[] = [
  { g: { ko: '빨리 받아야 할 때', en: 'Need it soon' }, items: [
    { text: { ko: '화이트 스니커즈 내일까지', en: 'white sneakers by tomorrow' } },
    { text: { ko: '검정 울 코트 금요일까지', en: 'black wool coat by friday' } },
  ] },
  { g: { ko: '예산 안에서', en: 'Within budget' }, items: [
    { text: { ko: '캐시미어 니트 20만원 이하', en: 'cashmere knit under 200000' } },
    { text: { ko: '바람막이 자켓 15만원 이하', en: 'windbreaker jacket under 150000' } },
    { text: { ko: '블랙 로퍼랑 블랙 슬랙스 합쳐서 30만원', en: 'black loafers and black slacks, total 300000' } },
  ] },
  { g: { ko: '한 번에 맞추기', en: 'A full look' }, items: [
    { text: { ko: '베이지 블레이저랑 화이트 셔츠랑 블랙 슬랙스', en: 'beige blazer, white shirt and black slacks' } },
    { text: { ko: '검정 울 코트 20만원 이하랑 검정 가죽 로퍼, 합쳐서 35만원', en: 'black wool coat under 200000 and black leather loafers, total 350000' }, label: { ko: '코트랑 로퍼, 합쳐서 35만원', en: 'Coat and loafers, 350000 total' } },
  ] },
  { g: { ko: '사이즈를 정해서', en: 'In my size' }, items: [
    { text: { ko: '검정 울 코트 XL', en: 'black wool coat, size XL' } },
    { text: { ko: '데님 와이드 팬츠 30사이즈', en: 'denim pants, size 30' } },
    { text: { ko: '화이트 스니커즈 280', en: 'white sneakers, size 280' } },
  ] },
  { g: { ko: '대충 말해도', en: 'Loosely put' }, items: [
    { text: { ko: '가을에 입기 좋은 자켓', en: 'jacket for autumn' } },
    { text: { ko: '출근용 블랙 가죽 가방', en: 'black leather bag for work' } },
    { text: { ko: '코트 힙한 느낌', en: 'coat hype vibe' } },
  ] },
];

export const PRESETS = SUGGEST.flatMap((g) => g.items);

export const DIAL: Record<Dial, L> = {
  always: { ko: '매번 확인', en: 'Every step' },
  'cart-only': { ko: '담기만 확인', en: 'Cart only' },
  auto: { ko: '알아서', en: 'Auto' },
};

export const LEVEL: Record<Level, L> = {
  high: { ko: '확신 높음', en: 'High confidence' },
  medium: { ko: '확신 보통', en: 'Medium confidence' },
  low: { ko: '확신 낮음', en: 'Low confidence' },
};

export const PHASE: Record<Phase, L> = {
  idle: { ko: '맡길 일을 기다려요', en: 'Ready when you are' },
  planning: { ko: '요청을 읽는 중', en: 'Reading your request' },
  'awaiting-approval': { ko: '승인을 기다려요', en: 'Waiting for approval' },
  executing: { ko: '찾고 비교하는 중', en: 'Searching and comparing' },
  'needs-input': { ko: '답을 기다려요', en: 'Waiting for your answer' },
  'payment-gate': { ko: '결제 승인을 기다려요', en: 'Waiting for payment approval' },
  done: { ko: '완료', en: 'Done' },
  failed: { ko: '실패', en: 'Failed' },
  cancelled: { ko: '중단됨', en: 'Stopped' },
  undone: { ko: '되돌림', en: 'Undone' },
};

export const money = (n: number, lang: Lang) =>
  lang === 'ko' ? `${n.toLocaleString('ko-KR')}원` : `KRW ${n.toLocaleString('en-US')}`;
